use super::{
    admin_access, admin_account_context, admin_account_security, admin_account_sessions,
    admin_application_authorization_preview, admin_application_authorization_read,
    admin_application_authorization_write, admin_application_auto_discovery,
    admin_application_billing, admin_application_crud, admin_application_directory_sync,
    admin_application_discovery, admin_application_enrollment, admin_application_iap,
    admin_application_jwt, admin_application_modules, admin_application_oidc,
    admin_application_scim, admin_audit, admin_auth, admin_authorization_code_read,
    admin_authorization_code_write, admin_client_response, admin_organizations, admin_providers,
    admin_security, admin_settings, admin_user_access, admin_user_directory, admin_user_import,
    admin_users, get_mutation_receipt,
};
use crate::AppState;
use axum::{
    Router,
    routing::{delete, get, post, put},
};

pub(super) fn routes() -> Router<AppState> {
    Router::new()
        .route("/api/login", post(admin_auth::login))
        .route("/api/logout", post(admin_auth::logout))
        .route("/api/me", get(admin_account_context::me))
        .route(
            "/api/me/organizations",
            get(admin_account_context::my_organizations)
                .post(admin_account_context::create_my_organization),
        )
        .route(
            "/api/me/organization-context",
            get(admin_account_context::my_organization_context)
                .put(admin_account_context::set_my_organization_context),
        )
        .route("/api/csrf", get(admin_security::csrf_token))
        .route(
            "/api/me/sessions",
            get(admin_account_sessions::list_my_sessions),
        )
        .route(
            "/api/me/sessions/{session_id}",
            delete(admin_account_sessions::revoke_my_session),
        )
        .route(
            "/api/me/consents",
            get(admin_account_sessions::list_my_consents),
        )
        .route(
            "/api/me/consents/{client_id}",
            get(admin_account_sessions::get_my_consent)
                .delete(admin_account_sessions::revoke_my_consent),
        )
        .route("/api/mfa/status", get(admin_account_security::mfa_status))
        .route(
            "/api/mfa/totp",
            post(admin_account_security::start_totp_setup)
                .delete(admin_account_security::disable_mfa),
        )
        .route(
            "/api/mfa/totp/confirm",
            post(admin_account_security::confirm_totp_setup),
        )
        .route(
            "/api/mfa/recovery-codes/rotate",
            post(admin_account_security::rotate_recovery_codes),
        )
        .route("/api/admin/overview", get(super::admin_overview::overview))
        .route("/api/admin/settings", get(admin_settings::settings_summary))
        .route(
            "/api/admin/registration-settings",
            get(admin_settings::get_registration_settings)
                .put(admin_settings::update_registration_settings),
        )
        .route(
            "/api/admin/runtime-settings",
            get(admin_settings::get_runtime_settings).put(admin_settings::update_runtime_settings),
        )
        .route(
            "/api/admin/login-settings",
            get(admin_settings::get_login_settings).put(admin_settings::update_login_settings),
        )
        .route(
            "/api/admin/security-policy",
            get(admin_settings::get_security_policy).put(admin_settings::update_security_policy),
        )
        .route(
            "/api/admin/signing-keys",
            get(admin_settings::list_signing_keys).post(admin_settings::rotate_signing_key),
        )
        .route(
            "/api/admin/users",
            get(admin_user_directory::list_users).post(admin_users::create_user),
        )
        .route(
            "/api/admin/users/page",
            get(admin_user_directory::list_users),
        )
        .route(
            "/api/admin/users/cursor",
            get(admin_user_directory::list_users_cursor),
        )
        .route(
            "/api/admin/user-options",
            get(admin_user_directory::list_user_options),
        )
        .route(
            "/api/admin/users/import-csv",
            post(admin_user_import::import_users_csv),
        )
        .route(
            "/api/admin/users/bulk-lifecycle",
            post(admin_users::bulk_user_lifecycle),
        )
        .route(
            "/api/admin/users/{id}",
            get(admin_user_directory::user_detail)
                .put(admin_users::update_user)
                .delete(admin_users::delete_user),
        )
        .route(
            "/api/admin/users/{id}/enable",
            post(admin_users::enable_user),
        )
        .route(
            "/api/admin/users/{id}/password",
            post(admin_users::set_user_password),
        )
        .route(
            "/api/admin/users/{id}/mfa/reset",
            post(admin_users::reset_user_mfa),
        )
        .route(
            "/api/admin/users/{id}/login-events",
            get(admin_user_directory::user_login_events),
        )
        .route(
            "/api/admin/users/{id}/permissions",
            get(admin_user_directory::user_permissions),
        )
        .route(
            "/api/admin/clients",
            get(admin_client_response::list_clients),
        )
        .route(
            "/api/admin/applications",
            get(admin_application_crud::list_applications)
                .post(admin_application_crud::create_application),
        )
        .route(
            "/api/admin/applications/{id}",
            put(admin_application_crud::update_application)
                .delete(admin_application_crud::delete_application),
        )
        .route(
            "/api/admin/applications/{id}/discovery",
            get(admin_application_discovery::get).put(admin_application_discovery::update),
        )
        .route(
            "/api/admin/applications/{id}/discovery/sync",
            post(admin_application_discovery::sync),
        )
        .route(
            "/api/admin/applications/{id}/client-bindings",
            get(admin_application_crud::list_application_client_bindings),
        )
        .route(
            "/api/admin/application-discovery/discover",
            post(admin_application_auto_discovery::discover),
        )
        .route(
            "/api/admin/applications/{id}/oidc-clients",
            get(admin_application_oidc::list).post(admin_application_oidc::create),
        )
        .route(
            "/api/admin/applications/{id}/oidc-clients/{client_id}",
            put(admin_application_oidc::update).delete(admin_application_oidc::delete),
        )
        .route(
            "/api/admin/applications/{id}/modules",
            get(admin_application_modules::list),
        )
        .route(
            "/api/admin/applications/{id}/modules/{module_key}",
            put(admin_application_modules::update).delete(admin_application_modules::delete),
        )
        .route(
            "/api/admin/applications/{id}/billing-settings",
            get(admin_application_billing::get).put(admin_application_billing::update),
        )
        .route(
            "/api/admin/applications/{id}/iap-rules",
            get(admin_application_iap::list_application_iap_rules)
                .post(admin_application_iap::create_application_iap_rule),
        )
        .route(
            "/api/admin/applications/{id}/iap-rules/{rule_id}",
            put(admin_application_iap::update_application_iap_rule)
                .delete(admin_application_iap::delete_application_iap_rule),
        )
        .route(
            "/api/admin/applications/{id}/directory-sync/runs",
            get(admin_application_directory_sync::list_runs),
        )
        .route(
            "/api/admin/applications/{id}/directory-sync/{provider_id}/run",
            post(admin_application_directory_sync::run),
        )
        .route(
            "/api/admin/applications/{id}/jwt-client",
            get(admin_application_jwt::get).put(admin_application_jwt::update),
        )
        .route(
            "/api/admin/applications/{id}/jwt-client/secret",
            post(admin_application_jwt::rotate_secret),
        )
        .route(
            "/api/admin/applications/{id}/jwt-client/secrets",
            delete(admin_application_jwt::revoke_secrets),
        )
        .route(
            "/api/admin/applications/{id}/scim-tokens",
            get(admin_application_scim::list).post(admin_application_scim::create),
        )
        .route(
            "/api/admin/applications/{id}/scim-tokens/{token_id}",
            delete(admin_application_scim::revoke),
        )
        .route(
            "/api/admin/applications/{id}/authorization/catalog",
            get(admin_application_authorization_read::catalog),
        )
        .route(
            "/api/admin/applications/{id}/authorization/profiles",
            get(admin_application_authorization_read::list_profiles),
        )
        .route(
            "/api/admin/applications/{id}/authorization/profiles/{profile_id}",
            get(admin_application_authorization_read::get_profile),
        )
        .route(
            "/api/admin/applications/{id}/authorization/profiles/{profile_id}/catalog",
            get(admin_application_authorization_read::profile_catalog),
        )
        .route(
            "/api/admin/applications/{id}/authorization/profiles/{profile_id}/bindings",
            get(admin_application_authorization_write::get_bindings)
                .put(admin_application_authorization_write::update_bindings),
        )
        .route(
            "/api/admin/applications/{id}/authorization/profiles/{profile_id}/roles",
            get(admin_application_authorization_write::list_roles)
                .post(admin_application_authorization_write::create_role),
        )
        .route(
            "/api/admin/applications/{id}/authorization/profiles/{profile_id}/roles/{role_id}",
            put(admin_application_authorization_write::update_role)
                .delete(admin_application_authorization_write::delete_role),
        )
        .route(
            "/api/admin/applications/{id}/authorization/profiles/{profile_id}/{user_id}",
            get(admin_application_authorization_preview::profile),
        )
        .route(
            "/api/admin/applications/{id}/authorization/subjects",
            get(admin_application_authorization_read::subjects),
        )
        .route(
            "/api/admin/applications/{id}/authorization/{user_id}",
            get(admin_application_authorization_preview::application),
        )
        .route(
            "/api/admin/applications/{id}/enrollment-codes",
            get(admin_application_enrollment::list_application_enrollment_codes)
                .post(admin_application_enrollment::create_application_enrollment_code),
        )
        .route(
            "/api/admin/applications/{id}/enrollment-codes/{code_id}",
            delete(admin_application_enrollment::delete_application_enrollment_code),
        )
        .route(
            "/api/admin/iap-applications",
            get(admin_application_iap::list_iap_applications),
        )
        .route(
            "/api/admin/audit-events",
            get(admin_audit::list_audit_events),
        )
        .route("/api/admin/mutations/{id}", get(get_mutation_receipt))
        .route(
            "/api/admin/audit-webhooks",
            get(admin_audit::list_audit_webhooks).post(admin_audit::create_audit_webhook),
        )
        .route(
            "/api/admin/audit-webhooks/{id}",
            put(admin_audit::update_audit_webhook).delete(admin_audit::delete_audit_webhook),
        )
        .route(
            "/api/admin/access/permissions",
            get(admin_access::list_permissions),
        )
        .route(
            "/api/admin/access/roles",
            get(admin_access::list_roles).post(admin_access::create_role),
        )
        .route(
            "/api/admin/access/roles/{id}",
            put(admin_access::update_role).delete(admin_access::delete_role),
        )
        .route(
            "/api/admin/access/groups",
            get(admin_access::list_groups).post(admin_access::create_group),
        )
        .route(
            "/api/admin/access/groups/{id}",
            put(admin_access::update_group).delete(admin_access::delete_group),
        )
        .route(
            "/api/admin/access/groups/{id}/roles",
            put(admin_access::update_group_roles),
        )
        .route(
            "/api/admin/access/groups/{id}/members",
            put(admin_access::update_group_members),
        )
        .route(
            "/api/admin/organizations",
            get(admin_organizations::list_organizations)
                .post(admin_organizations::create_organization),
        )
        .route(
            "/api/admin/organization-options",
            get(admin_organizations::list_organization_options),
        )
        .route(
            "/api/admin/organizations/{id}",
            put(admin_organizations::update_organization)
                .delete(admin_organizations::delete_organization),
        )
        .route(
            "/api/admin/organizations/{id}/members",
            get(admin_organizations::list_organization_members)
                .post(admin_organizations::upsert_organization_member)
                .put(admin_organizations::update_organization_members),
        )
        .route(
            "/api/admin/organizations/{id}/member-invitations",
            get(admin_organizations::list_organization_member_invitations)
                .post(admin_organizations::create_organization_member_invitation),
        )
        .route(
            "/api/admin/organizations/{id}/member-invitations/{invitation_id}",
            delete(admin_organizations::delete_organization_member_invitation),
        )
        .route(
            "/api/admin/users/{id}/access",
            get(admin_user_access::user_access),
        )
        .route(
            "/api/admin/users/{id}/roles",
            put(admin_user_access::update_user_roles),
        )
        .route(
            "/api/admin/authorization-codes",
            get(admin_authorization_code_read::list_invitations)
                .post(admin_authorization_code_write::create_invitation),
        )
        .route(
            "/api/admin/authorization-codes/{id}/reveal",
            post(admin_authorization_code_read::reveal_invitation_code),
        )
        .route(
            "/api/admin/authorization-codes/{id}/redemptions",
            get(admin_authorization_code_read::list_invitation_redemptions),
        )
        .route(
            "/api/admin/authorization-codes/{id}",
            put(admin_authorization_code_write::update_invitation)
                .delete(admin_authorization_code_write::delete_invitation),
        )
        .route(
            "/api/admin/invitations",
            get(admin_authorization_code_read::list_invitations)
                .post(admin_authorization_code_write::create_invitation),
        )
        .route(
            "/api/admin/invitations/{id}/reveal",
            post(admin_authorization_code_read::reveal_invitation_code),
        )
        .route(
            "/api/admin/invitations/{id}/redemptions",
            get(admin_authorization_code_read::list_invitation_redemptions),
        )
        .route(
            "/api/admin/invitations/{id}",
            put(admin_authorization_code_write::update_invitation)
                .delete(admin_authorization_code_write::delete_invitation),
        )
        .route(
            "/api/admin/external-oidc-providers",
            get(admin_providers::list_external_oidc_providers)
                .post(admin_providers::create_external_oidc_provider),
        )
        .route(
            "/api/admin/external-oidc-provider-templates",
            get(admin_providers::list_external_oidc_provider_templates),
        )
        .route(
            "/api/admin/external-oidc-provider-discovery",
            post(admin_providers::discover_external_oidc_provider),
        )
        .route(
            "/api/admin/external-oidc-providers/{id}",
            put(admin_providers::update_external_oidc_provider)
                .delete(admin_providers::delete_external_oidc_provider),
        )
        .route(
            "/api/admin/ldap-providers",
            get(admin_providers::list_ldap_providers).post(admin_providers::create_ldap_provider),
        )
        .route(
            "/api/admin/ldap-providers/{id}",
            put(admin_providers::update_ldap_provider)
                .delete(admin_providers::delete_ldap_provider),
        )
}
